const AVAILABLE_VARIABLES = [
    { key: "header_line1", desc: "السطر الأول من الرأسية" },
    { key: "header_line2", desc: "السطر الثاني" },
    { key: "entity_name", desc: "اسم الجهة / الشركة" },
    { key: "document_number", desc: "رقم المستند" },
    { key: "document_date", desc: "تاريخ المستند" },
    { key: "warehouse_name", desc: "اسم المخزن" },
    { key: "warehouse_code", desc: "رمز المخزن" },
    { key: "center_cost", desc: "رقم مركز الكلفة" },
    { key: "center_cost_name", desc: "اسم مركز الكلفة" },
    { key: "account_number", desc: "رقم الحساب" },
    { key: "type_movement", desc: "نوع الحركة" },
    { key: "type_movement_code", desc: "رمز نوع الحركة" },
    { key: "beneficiary", desc: "المستفيد" },
    { key: "user_name", desc: "اسم المستخدم" },
    { key: "factory_name", desc: "اسم المعمل" },
    { key: "lab_name", desc: "اسم المختبر" },
    { key: "description", desc: "الملاحظات" },
    { key: "items_table", desc: "جدول مواد كامل تلقائي" },
    { key: "items_rows", desc: "صفوف البيانات فقط" },
    { key: "items_count", desc: "عدد البنود" },
    { key: "total_quantity", desc: "إجمالي الكمية" },
    { key: "total_price", desc: "القيمة الإجمالية" },
    { key: "dynamic_fields", desc: "الحقول الديناميكية" },
    { key: "signatures", desc: "كل التوقيعات" },
    { key: "signature_1", desc: "توقيع 1" },
    { key: "signature_2", desc: "توقيع 2" },
    { key: "signature_3", desc: "توقيع 3" },
    { key: "signature_4", desc: "توقيع 4" },
    { key: "items_loop_start", desc: "بداية حلقة المواد" },
    { key: "items_loop_end", desc: "نهاية حلقة المواد" },
    { key: "item_index", desc: "تسلسل المادة" },
    { key: "item_code", desc: "رمز المادة" },
    { key: "item_name", desc: "اسم المادة" },
    { key: "item_qty", desc: "الكمية" },
    { key: "item_unit", desc: "وحدة القياس" },
    { key: "item_price", desc: "سعر الوحدة" },
    { key: "item_total", desc: "المبلغ الإجمالي" },
    { key: "item_spec", desc: "المواصفات" },
    { key: "item_date", desc: "تاريخ الشراء" },
    { key: "item_work_order", desc: "رقم أمر العمل" },
    { key: "item_notes", desc: "ملاحظات" },
    {key:"item_export" , desc:"تاريخ التصدير"},
    {key:"item_inspection_number" , desc:"رقم الفحص"},
    {key:"item_inspection_date" , desc:"تاريخ الفحص"},
    {key:"item_return_date" , desc:"تاريخ الإرجاع"}
];

/* ══════════════════════════════════════════════════════
   ALL COLUMNS — each maps to a backend item_* placeholder
   ══════════════════════════════════════════════════════ */
const DEFAULT_COLUMNS = [
    { id: "index", placeholder: "item_index", label: "ت" },
    { id: "work_order", placeholder: "item_work_order", label: "رقم أمر العمل" },
    { id: "code", placeholder: "item_code", label: "رمز المادة" },
    { id: "name", placeholder: "item_name", label: "اسم المادة" },
    { id: "spec", placeholder: "item_spec", label: "المواصفات" },
    { id: "qty", placeholder: "item_qty", label: "الكمية" },
    { id: "unit", placeholder: "item_unit", label: "وحدة القياس" },
    { id: "price", placeholder: "item_price", label: "سعر الوحدة" },
    { id: "total", placeholder: "item_total", label: "المبلغ الإجمالي" },
    { id: "date", placeholder: "item_date", label: "تاريخ الشراء" },
    { id: "supplier", placeholder: "item_supplier", label: "الجهة الموردة" },
    { id: "export_date", placeholder: "item_export", label: "تاريخ التصدير" },
    {id:"notes",placeholder:"item_notes",label:"ملاحظات"},
    {id:"inspection_number",placeholder:"item_inspection_number",label:"رقم الفحص"},
    {id:"inspection_date",placeholder:"item_inspection_date",label:"تاريخ الفحص"},
    {id:"return_date",placeholder:"item_return_date",label:"تاريخ الإرجاع"}
];
export { AVAILABLE_VARIABLES, DEFAULT_COLUMNS };